name             'chefspec_bug'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures chefspec_bug'
long_description 'Installs/Configures chefspec_bug'
version          '0.1.0'
